ARG GO_VERSION=docker.io/golang
ARG KUBERNETES_GIT_TAG=1.16.3

FROM ${GO_VERSION}

WORKDIR /go/src/github.com/jcodybaker/wgmesh

ENV GOPATH /go
COPY . /go/src/github.com/jcodybaker/wgmesh

RUN go mod download

# k8s.io/code-generator 
RUN cd /go && \
  (GO111MODULE=off go get k8s.io/code-generator || true) && \
  cd /go/src/k8s.io/code-generator && \
  git checkout ${KUBERNETES_GIT_TAG}