apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: wgmesh
  name: wgmesh
spec:
  selector:
    matchLabels:
      app: wgmesh
  template:
    metadata:
      annotations:
      labels:
        app: wgmesh
    spec:
      containers:
      - command:
        - /app/wgmesh
        - --name=$(K8S_NODE_NAME)
        - --kube-namespace=wg
        - --debug
        - --keepalive-seconds=25
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: docker.io/jcodybaker/wgmesh:latest
        imagePullPolicy: Always
        name: wgmesh-agent
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      securityContext: {}
      serviceAccount: wgmesh
      serviceAccountName: wgmesh
      terminationGracePeriodSeconds: 1
      tolerations:
      - operator: Exists